### ISSUE TITLE
 invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by altjx** [urbanadventurer/urlcrazy#9]
Fresh install of the latest version of Kali's docker container, ran `apt install urlcrazy -y` and tried to run it. The following error appeared:

```
Traceback (most recent call last):
        6: from ./urlcrazy:57:in `<main>'
        5: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        4: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        3: from /usr/share/urlcrazy/common-misspellings.rb:3:in `<top (required)>'
        2: from /usr/share/urlcrazy/common-misspellings.rb:17:in `<class:CommonMisspellings>'
        1: from /usr/share/urlcrazy/common-misspellings.rb:17:in `delete_if'
/usr/share/urlcrazy/common-misspellings.rb:17:in `block in <class:CommonMisspellings>': invalid byte sequence in US-ASCII (ArgumentError)
```

**Comment by saberbenamira** [comment]
same problem......any solutions???

**Comment by altjx** [comment]
> invalid byte sequence in US-ASCII

In `common-misspellings.rb`, change line 17 from:

```
@@file_contents=File.readlines($LOAD_PATH.first + "/common-misspellings.txt").delete_if { |line| line =~ /^#/ or line =~ /^[ ]*$/ }.join
```

to

```
@@file_contents=File.readlines($LOAD_PATH.first + "/common-misspellings.txt", :encoding => 'UTF-8').delete_if { |line| line =~ /^#/ or line =~ /^[ ]*$/ }.join
```

**Comment by urbanadventurer** [comment]
I think this was resolved a while back. The latest release works fine on the latest Kali.
